# Generated by Django 4.2.7 on 2023-11-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("temperature_logger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("time", models.TimeField(unique=True)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="temperature_logger.datelog",
                    ),
                ),
            ],
            options={
                "unique_together": {("time", "date")},
            },
        ),
    ]
