# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temperature_logger", "0002_datelog_temperaturereading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperaturereading",
            name="time",
            field=models.TimeField(),
        ),
    ]
